version: "3"

services:
  flask_server:
    build: ./fact-bounty-flask
    ports:
      - 5000:5000
      
  client:
    build: ./fact-bounty-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development