// flow-typed signature: e608dacddc7fa875f4f23d31f7f19e8c
// flow-typed version: <<STUB>>/is-empty_v^1.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-empty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-empty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-empty/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-empty/lib/index.js' {
  declare module.exports: $Exports<'is-empty/lib/index'>;
}
