// flow-typed signature: 1f635bee85365420f3e58b1e258bc2cf
// flow-typed version: <<STUB>>/react-lines-ellipsis_v^0.14.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lines-ellipsis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lines-ellipsis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lines-ellipsis/lib/common' {
  declare module.exports: any;
}

declare module 'react-lines-ellipsis/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-lines-ellipsis/lib/html' {
  declare module.exports: any;
}

declare module 'react-lines-ellipsis/lib/index' {
  declare module.exports: any;
}

declare module 'react-lines-ellipsis/lib/loose' {
  declare module.exports: any;
}

declare module 'react-lines-ellipsis/lib/responsiveHOC' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lines-ellipsis/lib/common.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/common'>;
}
declare module 'react-lines-ellipsis/lib/helpers.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/helpers'>;
}
declare module 'react-lines-ellipsis/lib/html.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/html'>;
}
declare module 'react-lines-ellipsis/lib/index.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/index'>;
}
declare module 'react-lines-ellipsis/lib/loose.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/loose'>;
}
declare module 'react-lines-ellipsis/lib/responsiveHOC.js' {
  declare module.exports: $Exports<'react-lines-ellipsis/lib/responsiveHOC'>;
}
