"""empty message

Revision ID: 78d18dc2789d
Revises: d2fc5d7ff47e
Create Date: 2020-01-25 10:50:19.720464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78d18dc2789d"
down_revision = "d2fc5d7ff47e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "user", sa.Column("role", sa.String(length=60), nullable=True)
    )
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    op.drop_column("user", "role")
    op.drop_table("comment")
    op.drop_table("revoked_tokens")
    # ### end Alembic commands ###
