version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/fact-bounty-client"
    update_schedule: "live"

  - package_manager: "python"
    directory: "/fact-bounty-flask"
    update_schedule: "live"